name: "Build diploma"
on:
  push:
    branches:
      - master
    tags:
    - '*'
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker run -v $PWD:"/work" -w /work texlive/texlive pdflatex "arutyunov - thesis.tex"
    - uses: softprops/action-gh-release@v1
      with:
        files: "arutyunov - thesis.pdf"
        name: latest
        allowUpdates: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

