name: "Build diploma"
on:
  push:
    branches:
      - master
    tags:
    - '*'
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v
    - uses: docker/build-push-action@v2
      with:
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new
        tags: latex
        context: .
        push: false
    - run: docker create --name img latex
    - run: docker cp "img:/work/arutyunov - thesis.pdf" "arutyunov - thesis.pdf"
    - run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
    - uses: softprops/action-gh-release@v1
      with:
        files: "arutyunov - thesis.pdf"
        name: latest
        allowUpdates: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

