name: "Build diploma"
on:
  push:
    branches:
      - master
    tags:
    - '*'
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: xu-cheng/latex-action@v2
      with:
        root_file: arutyunov-thesis.tex
    - uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: arutyunov-thesis.pdf
        tag: latest
        overwrite: true
        body: "My diploma, latest verrsion!"

