name: "Build diploma"
on:
  push:
    branches:
      - master
    tags:
    - '*'
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker build -t latex .
    - run: docker run -v $PWD:"/work" -w /work latex pdflatex arutyunov-thesis.tex
    - run: docker run -v $PWD:"/work" -w /work latex pdflatex arutyunov-thesis.tex
    - uses: softprops/action-gh-release@v1
      with:
        body: My diploma, latest verrsion!
        files: "arutyunov-thesis.pdf"
        tag_name: latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

