name: "Build diploma"
on:
  push:
    branches:
      - master
    tags:
    - '*'
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v2
      with:
        context: .
        push: false
    - uses: ncipollo/release-action@v1
      with:
        bodyFile: "arutyunov - thesis.pdf"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: latest
